//! Translating registry ids for older clients.
//!
//! Items, entity types, sounds and particles all travel as bare indices into registries whose
//! contents grow between releases. The indices are assigned in name order, so one added entry
//! shifts every id after it and a client reads whatever now sits at that index.
//!
//! The tables are generated by `scripts/build_registry_remap.py` from each version's own extracted
//! registry report, as a flat little-endian `u16` indexed by the server's own id.
//!
//! An id with no counterpart reads as [`NO_EQUIVALENT`] and the lookups return `None`. What to do
//! about that belongs to the caller and differs per registry: a sound or a particle is dropped,
//! since silence beats the wrong sound, while an item takes a stand-in from the same family so a
//! container slot still holds something.

use crate::encode::errors::NetEncodeError;
use crate::encode::{NetEncode, NetEncodeOpts};
use crate::net_types::var_int::VarInt;
use crate::version::ProtocolVersion;

/// Written into a table where the target version has nothing meaning the same thing.
const NO_EQUIVALENT: u16 = u16::MAX;

macro_rules! tables {
    ($registry:literal) => {
        [
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.2.bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.4.bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.5.bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.6.bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.8.bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.9.bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.11.bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/26.1.bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/26.2.bin"
            )),
        ]
    };
}

/// One table per supported version, in the order of [`ProtocolVersion::ALL`].
static ITEM: [&[u8]; 10] = tables!("item");
static ENTITY_TYPE: [&[u8]; 10] = tables!("entity_type");
static SOUND: [&[u8]; 10] = tables!("sound_event");
static PARTICLE: [&[u8]; 10] = tables!("particle_type");
static MOB_EFFECT: [&[u8]; 10] = tables!("mob_effect");
static ATTRIBUTE: [&[u8]; 10] = tables!("attribute");

fn lookup(tables: &[&[u8]; 10], id: u32, version: ProtocolVersion) -> Option<u32> {
    let table = tables[version.index()];
    let offset = id as usize * 2;
    let entry = match table.get(offset..offset + 2) {
        Some([low, high]) => u16::from_le_bytes([*low, *high]),
        // Past the end of the table means an id this server does not generate. Leaving it alone is
        // no worse than guessing at it.
        _ => return Some(id),
    };
    (entry != NO_EQUIVALENT).then_some(u32::from(entry))
}

/// The id `item` has in `version`, or `None` where that version has nothing of the kind.
#[must_use]
pub fn item_for(item: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&ITEM, item, version)
}

/// The id `entity_type` has in `version`. `None` means the version has no such entity, and the
/// packet spawning it should not be sent rather than spawning something else.
#[must_use]
pub fn entity_type_for(entity_type: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&ENTITY_TYPE, entity_type, version)
}

/// The id `sound` has in `version`. `None` means the version has no such sound, and playing
/// nothing is better than playing another one.
#[must_use]
pub fn sound_for(sound: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&SOUND, sound, version)
}

/// The id `particle` has in `version`. `None` means the version has no such particle.
#[must_use]
pub fn particle_for(particle: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&PARTICLE, particle, version)
}

/// The id `effect` has in `version`. `None` means the version has no such effect, and a packet
/// applying it says nothing rather than applying another one.
#[must_use]
pub fn mob_effect_for(effect: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&MOB_EFFECT, effect, version)
}

/// The id `attribute` has in `version`. `None` means the version has no such attribute, and the
/// snapshot carrying it is left out rather than named as another one: a client told the wrong
/// attribute applies a modifier to the wrong number.
///
/// 1.21 filed these under the group they belonged to — `generic.armor` rather than `armor` — so
/// the tables follow that rename exactly rather than guessing at a stand-in.
#[must_use]
pub fn attribute_for(attribute: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&ATTRIBUTE, attribute, version)
}

/// The id every version gives to air, which reads as an empty slot.
const AIR: u32 = 0;

/// Builds a wire id that translates itself to the reader's version as it is encoded.
///
/// A packet is broadcast to players who need not share a protocol version, so the translation
/// cannot happen when the packet is built - only when it is encoded for one particular connection.
macro_rules! network_id {
    ($name:ident, $lookup:path, $registry:literal, $absent:expr) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub struct $name(pub u32);

        impl $name {
            fn resolve(&self, version: ProtocolVersion) -> Result<u32, NetEncodeError> {
                match $lookup(self.0, version) {
                    Some(id) => Ok(id),
                    None => $absent(self.0, version),
                }
            }
        }

        impl NetEncode for $name {
            fn encode<W: std::io::Write>(
                &self,
                writer: &mut W,
                opts: &NetEncodeOpts,
            ) -> Result<(), NetEncodeError> {
                VarInt::new(self.resolve(opts.version)? as i32).encode(writer, opts)
            }

            async fn encode_async<W: tokio::io::AsyncWrite + Unpin>(
                &self,
                writer: &mut W,
                opts: &NetEncodeOpts,
            ) -> Result<(), NetEncodeError> {
                VarInt::new(self.resolve(opts.version)? as i32)
                    .encode_async(writer, opts)
                    .await
            }
        }
    };
}

/// An item with no stand-in in the reader's version becomes air, which reads as an empty slot.
/// Showing nothing is less misleading than showing something else in a slot a player can take from.
fn item_absent(_id: u32, _version: ProtocolVersion) -> Result<u32, NetEncodeError> {
    Ok(AIR)
}

/// Everything but items refuses instead, and the send paths drop the packet for that recipient.
/// A wrong entity, sound or particle is worse than none.
fn refuse(registry: &'static str) -> impl Fn(u32, ProtocolVersion) -> Result<u32, NetEncodeError> {
    move |id, version| {
        Err(NetEncodeError::NoSuchId {
            registry,
            id,
            version,
        })
    }
}

network_id!(NetworkItemId, item_for, "item", item_absent);
network_id!(
    NetworkEntityType,
    entity_type_for,
    "entity type",
    refuse("entity type")
);
network_id!(NetworkSound, sound_for, "sound", refuse("sound"));
network_id!(
    NetworkParticle,
    particle_for,
    "particle",
    refuse("particle")
);
network_id!(
    NetworkMobEffect,
    mob_effect_for,
    "mob effect",
    refuse("mob effect")
);

/// An attribute, written the way a registry entry is: its place plus one, since zero means the
/// entry follows inline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NetworkAttribute(pub u32);

impl NetworkAttribute {
    /// Whether the reader's version has this attribute at all.
    #[must_use]
    pub fn known_to(self, version: ProtocolVersion) -> bool {
        attribute_for(self.0, version).is_some()
    }
}

impl NetEncode for NetworkAttribute {
    fn encode<W: std::io::Write>(
        &self,
        writer: &mut W,
        opts: &NetEncodeOpts,
    ) -> Result<(), NetEncodeError> {
        let id = attribute_for(self.0, opts.version).ok_or(NetEncodeError::NoSuchId {
            registry: "attribute",
            id: self.0,
            version: opts.version,
        })?;
        VarInt::new(id as i32 + 1).encode(writer, opts)
    }

    async fn encode_async<W: tokio::io::AsyncWrite + Unpin>(
        &self,
        writer: &mut W,
        opts: &NetEncodeOpts,
    ) -> Result<(), NetEncodeError> {
        let mut buffer = Vec::new();
        self.encode(&mut buffer, opts)?;
        buffer.encode_async(writer, opts).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The server's own version maps every id to itself.
    #[test]
    fn the_native_tables_are_identities() {
        for id in [0, 1, 100, 1000] {
            assert_eq!(item_for(id, ProtocolVersion::CURRENT), Some(id));
            assert_eq!(sound_for(id, ProtocolVersion::CURRENT), Some(id));
        }
        for id in [0, 1, 100] {
            assert_eq!(entity_type_for(id, ProtocolVersion::CURRENT), Some(id));
            assert_eq!(particle_for(id, ProtocolVersion::CURRENT), Some(id));
        }
    }

    /// Air is the first item in every version, and stone the second, so an older version has to
    /// agree about both. A table built against the wrong registry would not.
    #[test]
    fn the_first_items_line_up_everywhere() {
        for version in ProtocolVersion::ALL {
            assert_eq!(item_for(0, version), Some(0), "air moved in {version}");
            assert_eq!(item_for(1, version), Some(1), "stone moved in {version}");
        }
    }

    /// Something added since 1.21 has no id there. If everything resolved, the tables would not be
    /// doing anything.
    #[test]
    fn older_versions_are_missing_things() {
        let missing = (0..1500)
            .filter(|&id| entity_type_for(id, ProtocolVersion::OLDEST).is_none())
            .count();
        assert!(missing > 0, "1.21 should be missing entity types");
    }
}
