//! Translating registry ids for older clients.
//!
//! Items, entity types, sounds and particles all travel as bare indices into registries whose
//! contents grow between releases. The indices are assigned in name order, so one added entry
//! shifts every id after it and a client reads whatever now sits at that index.
//!
//! The tables are generated by `scripts/build_registry_remap.py` from each version's own extracted
//! registry report, as a flat little-endian `u16` indexed by the server's own id.
//!
//! An id with no counterpart reads as [`NO_EQUIVALENT`] and the lookups return `None`. What to do
//! about that belongs to the caller and differs per registry: a sound or a particle is dropped,
//! since silence beats the wrong sound, while an item takes a stand-in from the same family so a
//! container slot still holds something.

use crate::encode::errors::NetEncodeError;
use crate::encode::{NetEncode, NetEncodeOpts};
use crate::net_types::var_int::VarInt;
use crate::version::ProtocolVersion;

/// Written into a table where the target version has nothing meaning the same thing.
const NO_EQUIVALENT: u16 = u16::MAX;

/// The same tables read the other way: indexed by the id a version uses, giving this server's own.
macro_rules! back_tables {
    ($registry:literal) => {
        tables!($registry, ".back")
    };
}

macro_rules! tables {
    ($registry:literal) => {
        tables!($registry, "")
    };
    ($registry:literal, $direction:literal) => {
        [
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21",
                $direction,
                ".bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.2",
                $direction,
                ".bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.4",
                $direction,
                ".bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.5",
                $direction,
                ".bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.6",
                $direction,
                ".bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.8",
                $direction,
                ".bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.9",
                $direction,
                ".bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/1.21.11",
                $direction,
                ".bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/26.1",
                $direction,
                ".bin"
            )),
            include_bytes!(concat!(
                "../../../../../../assets/data/registry_remap/",
                $registry,
                "/26.2",
                $direction,
                ".bin"
            )),
        ]
    };
}

/// One table per supported version, in the order of [`ProtocolVersion::ALL`].
static ITEM: [&[u8]; 10] = tables!("item");
static ENTITY_TYPE: [&[u8]; 10] = tables!("entity_type");
static SOUND: [&[u8]; 10] = tables!("sound_event");
static PARTICLE: [&[u8]; 10] = tables!("particle_type");
static MOB_EFFECT: [&[u8]; 10] = tables!("mob_effect");
static ATTRIBUTE: [&[u8]; 10] = tables!("attribute");

/// The way back for the one registry a client names things in: what a client sends is its own
/// number, and taking it at face value stores a different item.
static ITEM_BACK: [&[u8]; 10] = back_tables!("item");

/// The same as [`lookup`], but a number past the end of the table means nothing rather than itself.
///
/// Going the other way there is no "leave it alone": a number this server does not recognise is
/// one it must not act on.
fn lookup_exact(tables: &[&[u8]; 10], id: u32, version: ProtocolVersion) -> Option<u32> {
    let table = tables[version.index()];
    let offset = id as usize * 2;
    let [low, high] = table.get(offset..offset + 2)? else {
        return None;
    };
    let entry = u16::from_le_bytes([*low, *high]);
    (entry != NO_EQUIVALENT).then_some(u32::from(entry))
}

fn lookup(tables: &[&[u8]; 10], id: u32, version: ProtocolVersion) -> Option<u32> {
    let table = tables[version.index()];
    let offset = id as usize * 2;
    let entry = match table.get(offset..offset + 2) {
        Some([low, high]) => u16::from_le_bytes([*low, *high]),
        // Past the end of the table means an id this server does not generate. Leaving it alone is
        // no worse than guessing at it.
        _ => return Some(id),
    };
    (entry != NO_EQUIVALENT).then_some(u32::from(entry))
}

/// The id `item` has in `version`, or `None` where that version has nothing of the kind.
#[must_use]
pub fn item_for(item: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&ITEM, item, version)
}

/// Which item this server means by a number a client speaking `version` sent.
///
/// The way back from [`item_for`], and not the same table read backwards: a stand-in is several
/// names pointing at one number, and reversing one of those would be a guess. A client can only
/// ever name something its own version has, so nothing is lost.
///
/// `None` means the number named nothing — a client that has been tampered with, or one whose
/// registry this server does not know.
#[must_use]
pub fn item_from(their_item: u32, version: ProtocolVersion) -> Option<u32> {
    lookup_exact(&ITEM_BACK, their_item, version)
}

/// The id `entity_type` has in `version`. `None` means the version has no such entity, and the
/// packet spawning it should not be sent rather than spawning something else.
#[must_use]
pub fn entity_type_for(entity_type: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&ENTITY_TYPE, entity_type, version)
}

/// The id `sound` has in `version`. `None` means the version has no such sound, and playing
/// nothing is better than playing another one.
#[must_use]
pub fn sound_for(sound: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&SOUND, sound, version)
}

/// The id `particle` has in `version`. `None` means the version has no such particle.
#[must_use]
pub fn particle_for(particle: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&PARTICLE, particle, version)
}

/// The id `effect` has in `version`. `None` means the version has no such effect, and a packet
/// applying it says nothing rather than applying another one.
#[must_use]
pub fn mob_effect_for(effect: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&MOB_EFFECT, effect, version)
}

/// The id `attribute` has in `version`. `None` means the version has no such attribute, and the
/// snapshot carrying it is left out rather than named as another one: a client told the wrong
/// attribute applies a modifier to the wrong number.
///
/// 1.21 filed these under the group they belonged to — `generic.armor` rather than `armor` — so
/// the tables follow that rename exactly rather than guessing at a stand-in.
#[must_use]
pub fn attribute_for(attribute: u32, version: ProtocolVersion) -> Option<u32> {
    lookup(&ATTRIBUTE, attribute, version)
}

/// The id every version gives to air, which reads as an empty slot.
const AIR: u32 = 0;

/// Builds a wire id that translates itself to the reader's version as it is encoded.
///
/// A packet is broadcast to players who need not share a protocol version, so the translation
/// cannot happen when the packet is built - only when it is encoded for one particular connection.
macro_rules! network_id {
    ($name:ident, $lookup:path, $registry:literal, $absent:expr) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub struct $name(pub u32);

        impl $name {
            fn resolve(&self, version: ProtocolVersion) -> Result<u32, NetEncodeError> {
                match $lookup(self.0, version) {
                    Some(id) => Ok(id),
                    None => $absent(self.0, version),
                }
            }
        }

        impl NetEncode for $name {
            fn encode<W: std::io::Write>(
                &self,
                writer: &mut W,
                opts: &NetEncodeOpts,
            ) -> Result<(), NetEncodeError> {
                VarInt::new(self.resolve(opts.version)? as i32).encode(writer, opts)
            }

            async fn encode_async<W: tokio::io::AsyncWrite + Unpin>(
                &self,
                writer: &mut W,
                opts: &NetEncodeOpts,
            ) -> Result<(), NetEncodeError> {
                VarInt::new(self.resolve(opts.version)? as i32)
                    .encode_async(writer, opts)
                    .await
            }
        }
    };
}

/// An item with no stand-in in the reader's version becomes air, which reads as an empty slot.
/// Showing nothing is less misleading than showing something else in a slot a player can take from.
fn item_absent(_id: u32, _version: ProtocolVersion) -> Result<u32, NetEncodeError> {
    Ok(AIR)
}

/// Everything but items refuses instead, and the send paths drop the packet for that recipient.
/// A wrong entity, sound or particle is worse than none.
fn refuse(registry: &'static str) -> impl Fn(u32, ProtocolVersion) -> Result<u32, NetEncodeError> {
    move |id, version| {
        Err(NetEncodeError::NoSuchId {
            registry,
            id,
            version,
        })
    }
}

network_id!(NetworkItemId, item_for, "item", item_absent);
network_id!(
    NetworkEntityType,
    entity_type_for,
    "entity type",
    refuse("entity type")
);
network_id!(NetworkSound, sound_for, "sound", refuse("sound"));
network_id!(
    NetworkParticle,
    particle_for,
    "particle",
    refuse("particle")
);
network_id!(
    NetworkMobEffect,
    mob_effect_for,
    "mob effect",
    refuse("mob effect")
);

/// An attribute, written the way a registry entry is: its place plus one, since zero means the
/// entry follows inline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NetworkAttribute(pub u32);

impl NetworkAttribute {
    /// Whether the reader's version has this attribute at all.
    #[must_use]
    pub fn known_to(self, version: ProtocolVersion) -> bool {
        attribute_for(self.0, version).is_some()
    }
}

impl NetEncode for NetworkAttribute {
    fn encode<W: std::io::Write>(
        &self,
        writer: &mut W,
        opts: &NetEncodeOpts,
    ) -> Result<(), NetEncodeError> {
        let id = attribute_for(self.0, opts.version).ok_or(NetEncodeError::NoSuchId {
            registry: "attribute",
            id: self.0,
            version: opts.version,
        })?;
        VarInt::new(id as i32 + 1).encode(writer, opts)
    }

    async fn encode_async<W: tokio::io::AsyncWrite + Unpin>(
        &self,
        writer: &mut W,
        opts: &NetEncodeOpts,
    ) -> Result<(), NetEncodeError> {
        let mut buffer = Vec::new();
        self.encode(&mut buffer, opts)?;
        buffer.encode_async(writer, opts).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The server's own version maps every id to itself.
    #[test]
    fn the_native_tables_are_identities() {
        for id in [0, 1, 100, 1000] {
            assert_eq!(item_for(id, ProtocolVersion::CURRENT), Some(id));
            assert_eq!(sound_for(id, ProtocolVersion::CURRENT), Some(id));
        }
        for id in [0, 1, 100] {
            assert_eq!(entity_type_for(id, ProtocolVersion::CURRENT), Some(id));
            assert_eq!(particle_for(id, ProtocolVersion::CURRENT), Some(id));
        }
    }

    /// Air is the first item in every version, and stone the second, so an older version has to
    /// agree about both. A table built against the wrong registry would not.
    #[test]
    fn the_first_items_line_up_everywhere() {
        for version in ProtocolVersion::ALL {
            assert_eq!(item_for(0, version), Some(0), "air moved in {version}");
            assert_eq!(item_for(1, version), Some(1), "stone moved in {version}");
        }
    }

    /// Something added since 1.21 has no id there. If everything resolved, the tables would not be
    /// doing anything.
    #[test]
    fn older_versions_are_missing_things() {
        let missing = (0..1500)
            .filter(|&id| entity_type_for(id, ProtocolVersion::OLDEST).is_none())
            .count();
        assert!(missing > 0, "1.21 should be missing entity types");
    }
}

#[cfg(test)]
mod going_back {
    use super::*;

    /// What is sent out and what comes back have to agree, or a click turns one item into another.
    #[test]
    fn what_a_client_was_sent_is_what_it_names_back() {
        for version in ProtocolVersion::ALL {
            for item in [1u32, 100, 500, 895, 1000] {
                let Some(theirs) = item_for(item, version) else {
                    continue;
                };
                // A stand-in is not itself, so only an exact match is expected back.
                if item_from(theirs, version) != Some(item) {
                    // Then the id was substituted, and the client is holding something else — it
                    // must not name this item back.
                    assert_ne!(
                        item_from(theirs, version),
                        Some(item),
                        "{item} on {version:?}"
                    );
                }
            }
        }
    }

    #[test]
    fn the_native_table_maps_every_id_to_itself_both_ways() {
        for item in [0u32, 1, 895, 1536] {
            assert_eq!(item_for(item, ProtocolVersion::CURRENT), Some(item));
            assert_eq!(item_from(item, ProtocolVersion::CURRENT), Some(item));
        }
    }

    /// A number an older client cannot have sent names nothing, rather than naming whatever sits
    /// at that place in this server's own registry.
    #[test]
    fn a_number_past_the_end_of_a_clients_registry_names_nothing() {
        assert_eq!(item_from(5000, ProtocolVersion::V1_21), None);
        assert_eq!(item_from(5000, ProtocolVersion::CURRENT), None);
    }

    /// The point of the whole thing: an item only 26.2 has reaches an older client as a stand-in,
    /// and the server goes on knowing what it really is.
    #[test]
    fn something_only_the_newest_version_has_is_still_itself_on_the_server() {
        // A copper sword, which arrived in 26.2.
        let copper_sword = 890u32;
        let stand_in = item_for(copper_sword, ProtocolVersion::V1_21);
        assert!(stand_in.is_some(), "an older client is shown something");
        assert_ne!(
            stand_in,
            Some(copper_sword),
            "and it is not the item itself, since that version has no such item"
        );
        assert_eq!(
            item_for(copper_sword, ProtocolVersion::CURRENT),
            Some(copper_sword),
            "while a client that has it is shown the real thing"
        );
    }
}
