[package]
name = "ferrumc-entities"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_ecs = { workspace = true }
bevy_math = { workspace = true }
tokio = { workspace = true }

ferrumc-core = { workspace = true }
ferrumc-inventories = { workspace = true }
ferrumc-nbt = { workspace = true }
ferrumc-net-codec = { workspace = true }
ferrumc-physics = { workspace = true }
ferrumc-registry = { workspace = true }
ferrumc-text = { workspace = true }
