// Include the file generated by `build.rs`
// This file contains all the static `phf::Map`s
include!(concat!(env!("OUT_DIR"), "/registry_data.rs"));

/// Initializes the game registry.
/// This is now a no-op (it does nothing) because all data is
/// loaded at compile time. It's called by main.rs and tests.
pub fn init() {
    // This function is now free!
}

/// Looks up an item's protocol ID (e.g., 840) from its name (e.g., "minecraft:apple").
/// This is an instant, compile-time map lookup.
pub fn lookup_item_protocol_id(name: &str) -> Option<i32> {
    ITEM_NAME_TO_ID.get(name).copied()
}

/// Looks up an item's name (e.g., "minecraft:apple") from its protocol ID (e.g., 840).
/// This is an instant, compile-time map lookup.
pub fn lookup_item_name(protocol_id: i32) -> Option<&'static str> {
    ITEM_ID_TO_NAME.get(&protocol_id).copied()
}

/// Looks up a block *name* (e.g., "minecraft:stone") from a protocol ID string.
/// This is an instant, compile-time map lookup.
pub fn lookup_blockstate_name(protocol_id: &str) -> Option<&'static str> {
    BLOCKSTATE_ID_TO_NAME.get(protocol_id).copied()
}

/// Looks up a block state ID string from an item ID string.
/// This is an instant, compile-time map lookup.
pub fn lookup_item_to_block_id_str(item_id_str: &str) -> Option<&'static str> {
    ITEM_ID_STR_TO_BLOCKSTATE_ID_STR.get(item_id_str).copied()
}

/// Looks up a block's hardness (e.g., 1.5 for stone) from its name.
/// This is an instant, compile-time map lookup.
pub fn lookup_block_hardness(block_name: &str) -> Option<f32> {
    BLOCK_NAME_TO_HARDNESS
        .get(block_name)
        .map(|hardness_u32| f32::from_bits(*hardness_u32))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper to ensure the registry is loaded before each test.
    /// This is now a no-op, but we'll keep it for good practice.
    fn setup() {
        init();
    }

    #[test]
    fn test_lookup_item_protocol_id() {
        setup(); // This function is now free, but we call it for consistency

        // Which number an item has moves with every release, so the numbers are not the subject
        // here: that a known item resolves to one at all is.
        for name in ["minecraft:apple", "minecraft:cobblestone"] {
            assert!(
                lookup_item_protocol_id(name).is_some(),
                "{name} should be in the item registry"
            );
        }
    }

    #[test]
    fn test_lookup_item_protocol_id_non_existent() {
        setup();
        let value = lookup_item_protocol_id("minecraft:non_existent_item");
        assert!(value.is_none());
    }

    #[test]
    fn test_lookup_item_name() {
        setup();

        // A round trip rather than a literal id, which would need editing every release and
        // would pass against a table left behind from an older one.
        let apple = lookup_item_protocol_id("minecraft:apple").expect("apples exist");
        assert_eq!(lookup_item_name(apple), Some("minecraft:apple"));
    }

    #[test]
    fn test_lookup_blockstate_stone() {
        setup(); // No-op, but good practice

        let stone_entry = lookup_blockstate_name("1");
        assert!(
            stone_entry.is_some(),
            "lookup_blockstate_name(\"1\") returned None"
        );
        assert_eq!(stone_entry.unwrap(), "minecraft:stone");
    }

    #[test]
    fn test_lookup_blockstate_grass() {
        setup();

        let grass_entry = lookup_blockstate_name("9");
        assert!(
            grass_entry.is_some(),
            "lookup_blockstate_name(\"9\") returned None"
        );
        assert_eq!(grass_entry.unwrap(), "minecraft:grass_block");
    }

    #[test]
    fn test_lookup_item_to_block_id() {
        setup();

        // Assuming item "1" (stone) maps to blockstate "1"
        let block_id_str = lookup_item_to_block_id_str("1");
        assert!(
            block_id_str.is_some(),
            "lookup_item_to_block_id_str(\"1\") returned None"
        );
        assert_eq!(block_id_str.unwrap(), "1");
    }
}
