//! Translating block state ids for older clients.
//!
//! Block state ids are a dense index over every block's property combinations, so one added
//! property value shifts every id after it. Between 1.21.4 and 26.2 that moves 25765 ids onto a
//! different block: a client of the older version reads 26.2's `diamond_ore` as
//! `jungle_hanging_sign`. Anything carrying a block state id therefore has to translate it before
//! it reaches a client that does not speak the server's own version.
//!
//! The tables are generated by `scripts/build_block_state_remap.py` from each version's own
//! extracted block report, as a flat little-endian `u16` indexed by the server's id.

use ferrumc_net_codec::encode::errors::NetEncodeError;
use ferrumc_net_codec::encode::{NetEncode, NetEncodeOpts};
use ferrumc_net_codec::net_types::var_int::VarInt;
use ferrumc_net_codec::version::ProtocolVersion;

/// One table per supported version, in the order of [`ProtocolVersion::ALL`].
static TABLES: [&[u8]; 10] = [
    include_bytes!("../../../../../assets/data/block_state_remap/1.21.bin"),
    include_bytes!("../../../../../assets/data/block_state_remap/1.21.2.bin"),
    include_bytes!("../../../../../assets/data/block_state_remap/1.21.4.bin"),
    include_bytes!("../../../../../assets/data/block_state_remap/1.21.5.bin"),
    include_bytes!("../../../../../assets/data/block_state_remap/1.21.6.bin"),
    include_bytes!("../../../../../assets/data/block_state_remap/1.21.8.bin"),
    include_bytes!("../../../../../assets/data/block_state_remap/1.21.9.bin"),
    include_bytes!("../../../../../assets/data/block_state_remap/1.21.11.bin"),
    include_bytes!("../../../../../assets/data/block_state_remap/26.1.bin"),
    include_bytes!("../../../../../assets/data/block_state_remap/26.2.bin"),
];

/// The id `state` has in `version`. Ids the target version does not know fall back to a block it
/// does, so the world stays solid rather than developing holes.
#[must_use]
pub fn block_state_for(state: u32, version: ProtocolVersion) -> u32 {
    let table = TABLES[version.index()];
    let offset = state as usize * 2;
    match table.get(offset..offset + 2) {
        Some([low, high]) => u32::from(u16::from_le_bytes([*low, *high])),
        // Beyond the table means the id is not one this server generates; leaving it alone is no
        // worse than guessing, and it keeps the lookup infallible on the chunk-encoding path.
        _ => state,
    }
}

/// A block state id on its way to a client, translated to that client's version as it is written.
///
/// Block updates are broadcast to everyone in range, and those players need not share a protocol
/// version, so the translation cannot happen when the packet is built - only when it is encoded
/// for one particular connection. Any packet field holding a block state should use this rather
/// than a bare `VarInt`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NetworkBlockState(pub u32);

impl From<crate::chunk::BlockStateId> for NetworkBlockState {
    fn from(state: crate::chunk::BlockStateId) -> Self {
        Self(state.raw())
    }
}

impl NetEncode for NetworkBlockState {
    fn encode<W: std::io::Write>(
        &self,
        writer: &mut W,
        opts: &NetEncodeOpts,
    ) -> Result<(), NetEncodeError> {
        VarInt::new(block_state_for(self.0, opts.version) as i32).encode(writer, opts)
    }

    async fn encode_async<W: tokio::io::AsyncWrite + Unpin>(
        &self,
        writer: &mut W,
        opts: &NetEncodeOpts,
    ) -> Result<(), NetEncodeError> {
        VarInt::new(block_state_for(self.0, opts.version) as i32)
            .encode_async(writer, opts)
            .await
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every entry has to resolve, or a chunk send would silently emit the fallback everywhere.
    #[test]
    fn tables_are_complete_and_aligned() {
        let expected = TABLES[ProtocolVersion::CURRENT.index()].len();
        for (index, table) in TABLES.iter().enumerate() {
            assert_eq!(table.len() % 2, 0, "table {index} is not whole u16s");
            assert_eq!(
                table.len(),
                expected,
                "table {index} has a different length"
            );
        }
    }

    /// The server's own version needs no translation, which makes the native path free.
    #[test]
    fn native_version_is_the_identity() {
        let count = TABLES[ProtocolVersion::CURRENT.index()].len() / 2;
        for state in 0..count as u32 {
            assert_eq!(
                block_state_for(state, ProtocolVersion::CURRENT),
                state,
                "state {state} is not itself in the native table"
            );
        }
    }

    /// The case that motivated all of this. Expected values read out of each version's own block
    /// report; without translation a 1.21.4 client renders id 5307 as a jungle hanging sign.
    #[test]
    fn moved_ids_land_on_the_same_block() {
        for (native, expected, what) in [
            (5307, 4329, "diamond_ore"),
            (1, 1, "stone, below the first divergence"),
            (85, 85, "bedrock, below the first divergence"),
        ] {
            assert_eq!(
                block_state_for(native, ProtocolVersion::V1_21_4),
                expected,
                "{what}: 26.2 state {native} should be {expected} in 1.21.4"
            );
        }
    }

    /// A block 1.21.4 does not have becomes one of the same family, keeping its properties so the
    /// shape is right: fully connected waterlogged copper bars become the same iron bars.
    #[test]
    fn an_absent_block_falls_back_within_its_family() {
        assert_eq!(block_state_for(7990, ProtocolVersion::V1_21_4), 6974);
    }
}
