#!/usr/bin/env python3
"""Generate src/lib/entities/src/entity_type/generated.rs from the extracted entity data.

The registry gives every entity type a number, and those numbers are contiguous from zero, so the
enum carries them as its own discriminants: what goes on the wire is the variant itself, and every
property of a type is one index into a flat table.

Run scripts/extract_entity_types.py first; the report the game publishes does not carry any of
this.

Usage:
    scripts/build_entity_types.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VERSION = "26.2"
SOURCE = REPO_ROOT / "assets" / "extracted" / VERSION / "entity_types.json"
OUT = REPO_ROOT / "src" / "lib" / "entities" / "src" / "entity_type" / "generated.rs"

# What vanilla writes for "never update this entity again".
NEVER = 2147483647


def variant(name: str) -> str:
    """`minecraft:acacia_boat` -> `AcaciaBoat`."""
    bare = name.removeprefix("minecraft:")
    return "".join(part.capitalize() for part in bare.split("_"))


def rust_float(value: float) -> str:
    text = repr(float(value))
    return f"{text}f32"


def main() -> None:
    data = json.loads(SOURCE.read_text())
    types = data["types"]
    categories = data["categories"]

    lines: list[str] = []
    add = lines.append

    add("//! Every entity type the game has, and what each one is.")
    add("//!")
    add(f"//! Generated by `scripts/build_entity_types.py` from the {VERSION} data. Do not edit.")
    add("//!")
    add("//! The variants carry the registry's own numbers, so the value that goes on the wire is")
    add("//! the variant itself rather than something looked up beside it.")
    add("")

    # The categories, in the order the game declares them.
    add("/// The group a type spawns and is counted in.")
    add("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    add("pub enum MobCategory {")
    for name in categories:
        add(f"    {variant(name)},")
    add("}")
    add("")
    add("/// What each category allows.")
    add("#[derive(Debug, Clone, Copy)]")
    add("pub struct CategoryDef {")
    add("    /// The name the data files use.")
    add("    pub name: &'static str,")
    add("    /// How many of this group may be in one chunk before no more spawn, or nothing")
    add("    /// where there is no limit.")
    add("    pub max_per_chunk: Option<u32>,")
    add("    /// Whether it counts as peaceful, which decides whether the difficulty removes it.")
    add("    pub friendly: bool,")
    add("    /// Whether one stays once spawned rather than despawning when nobody is near.")
    add("    pub persistent: bool,")
    add("    /// Past this many blocks from every player, one despawns at once.")
    add("    pub despawn_distance: u32,")
    add("    /// Within this many, one never despawns.")
    add("    pub no_despawn_distance: u32,")
    add("}")
    add("")
    add("impl MobCategory {")
    add("    /// What this category allows.")
    add("    #[must_use]")
    add("    pub const fn def(self) -> &'static CategoryDef {")
    add("        &CATEGORIES[self as usize]")
    add("    }")
    add("}")
    add("")
    add(f"static CATEGORIES: [CategoryDef; {len(categories)}] = [")
    for name, c in categories.items():
        add("    CategoryDef {")
        add(f'        name: "{name}",')
        limit = "None" if c["max_per_chunk"] < 0 else f"Some({c['max_per_chunk']})"
        add(f"        max_per_chunk: {limit},")
        add(f"        friendly: {str(c['friendly']).lower()},")
        add(f"        persistent: {str(c['persistent']).lower()},")
        add(f"        despawn_distance: {c['despawn_distance']},")
        add(f"        no_despawn_distance: {c['no_despawn_distance']},")
        add("    },")
    add("];")
    add("")

    add("/// Where a mob of a type may stand for it to spawn there.")
    add("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    add("pub enum SpawnPlacement {")
    add("    /// Anywhere at all.")
    add("    NoRestrictions,")
    add("    /// On a block that will hold it.")
    add("    OnGround,")
    add("    InWater,")
    add("    InLava,")
    add("}")
    add("")

    add("/// Which surface a spawn attempt is measured against.")
    add("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    add("pub enum SpawnHeightmap {")
    add("    MotionBlocking,")
    add("    MotionBlockingNoLeaves,")
    add("}")
    add("")

    add("/// What one entity type is.")
    add("#[derive(Debug, Clone, Copy)]")
    add("pub struct EntityDef {")
    add("    /// The name the registry gives it, namespace included.")
    add("    pub name: &'static str,")
    add("    pub category: MobCategory,")
    add("    /// How wide it is; an entity's box is square in plan.")
    add("    pub width: f32,")
    add("    pub height: f32,")
    add("    /// How far up the box it looks from.")
    add("    pub eye_height: f32,")
    add("    /// Whether the box stays this size whatever the entity is doing.")
    add("    pub fixed_size: bool,")
    add("    /// How many chunks away a client is still told about it.")
    add("    pub tracking_range: u8,")
    add("    /// How many ticks between updates, or nothing where it is never updated again.")
    add("    pub update_interval: Option<u32>,")
    add("    /// Whether it is written with the chunk it is in.")
    add("    pub serialize: bool,")
    add("    /// Whether a command may make one.")
    add("    pub summon: bool,")
    add("    pub fire_immune: bool,")
    add("    /// Whether it may spawn beyond the usual distance from a player.")
    add("    pub spawn_far_from_player: bool,")
    add("    /// Whether it survives the peaceful difficulty.")
    add("    pub allowed_in_peaceful: bool,")
    add("    pub placement: SpawnPlacement,")
    add("    pub heightmap: SpawnHeightmap,")
    add("    /// What a living one starts with, or nothing where it is not a living entity.")
    add("    pub max_health: Option<f32>,")
    add("}")
    add("")

    add("/// Every entity type, numbered as the registry numbers them.")
    add("///")
    add("/// This is the component an entity carries: there is nothing else to keep, since")
    add("/// everything the game says about a type is one index away from the variant.")
    add("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, bevy_ecs::prelude::Component)]")
    add("#[repr(u16)]")
    add("pub enum EntityType {")
    for t in types:
        add(f"    {variant(t['name'])} = {t['id']},")
    add("}")
    add("")

    add(f"/// One entry per type, in the order the variants are numbered.")
    add(f"pub(crate) static ENTITY_TYPES: [EntityDef; {len(types)}] = [")
    placements = {
        "no_restrictions": "NoRestrictions",
        "on_ground": "OnGround",
        "in_water": "InWater",
        "in_lava": "InLava",
    }
    heightmaps = {
        "MOTION_BLOCKING": "MotionBlocking",
        "MOTION_BLOCKING_NO_LEAVES": "MotionBlockingNoLeaves",
    }
    for t in types:
        interval = "None" if t["update_interval"] == NEVER else f"Some({t['update_interval']})"
        health = "None" if t["max_health"] is None else f"Some({rust_float(t['max_health'])})"
        add("    EntityDef {")
        add(f'        name: "{t["name"]}",')
        add(f"        category: MobCategory::{variant(t['category'])},")
        add(f"        width: {rust_float(t['width'])},")
        add(f"        height: {rust_float(t['height'])},")
        add(f"        eye_height: {rust_float(t['eye_height'])},")
        add(f"        fixed_size: {str(t['fixed_size']).lower()},")
        add(f"        tracking_range: {t['tracking_range']},")
        add(f"        update_interval: {interval},")
        add(f"        serialize: {str(t['serialize']).lower()},")
        add(f"        summon: {str(t['summon']).lower()},")
        add(f"        fire_immune: {str(t['fire_immune']).lower()},")
        add(f"        spawn_far_from_player: {str(t['spawn_far_from_player']).lower()},")
        add(f"        allowed_in_peaceful: {str(t['allowed_in_peaceful']).lower()},")
        add(f"        placement: SpawnPlacement::{placements[t['placement']]},")
        add(f"        heightmap: SpawnHeightmap::{heightmaps[t['heightmap']]},")
        add(f"        max_health: {health},")
        add("    },")
    add("];")
    add("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"{len(types)} entity types, {len(categories)} categories -> {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
