#!/usr/bin/env python3
"""Generate src/lib/entities/src/entity_type/generated.rs from the extracted entity data.

The registry gives every entity type a number, and those numbers are contiguous from zero, so the
enum carries them as its own discriminants: what goes on the wire is the variant itself, and every
property of a type is one index into a flat table.

Run scripts/extract_entity_types.py first; the report the game publishes does not carry any of
this.

Usage:
    scripts/build_entity_types.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VERSION = "26.2"
SOURCE = REPO_ROOT / "assets" / "extracted" / VERSION / "entity_types.json"
PHYSICS = REPO_ROOT / "assets" / "extracted" / VERSION / "entity_physics.json"
SPAWN_RULES = REPO_ROOT / "assets" / "extracted" / VERSION / "spawn_rules.json"

# The conditions shared by more than one kind of mob. The rest are one mob each and belong with
# that mob's behaviour; until then a type carrying one is not spawned at all, which is the safe way
# to be wrong.
SHARED_RULES = {
    "Mob.checkMobSpawnRules": "Standable",
    "Monster.checkMonsterSpawnRules": "Dark",
    "Monster.checkAnyLightMonsterSpawnRules": "AnyLight",
    "Monster.checkSurfaceMonstersSpawnRules": "DarkUnderSky",
    "Animal.checkAnimalSpawnRules": "Animal",
    "WaterAnimal.checkSurfaceWaterAnimalSpawnRules": "SurfaceWater",
    "AgeableWaterCreature.checkSurfaceAgeableWaterCreatureSpawnRules": "SurfaceWater",
}
OUT = REPO_ROOT / "src" / "lib" / "entities" / "src" / "entity_type" / "generated.rs"

# What vanilla writes for "never update this entity again".
NEVER = 2147483647


def variant(name: str) -> str:
    """`minecraft:acacia_boat` -> `AcaciaBoat`."""
    bare = name.removeprefix("minecraft:")
    return "".join(part.capitalize() for part in bare.split("_"))


def rust_float(value: float) -> str:
    text = repr(float(value))
    return f"{text}f32"


def main() -> None:
    data = json.loads(SOURCE.read_text())
    types = data["types"]
    physics = json.loads(PHYSICS.read_text())["types"]
    spawn_rules = json.loads(SPAWN_RULES.read_text())["rules"]
    missing = {entry["name"] for entry in types} - set(physics)
    if missing:
        raise SystemExit(f"no physics read for {sorted(missing)}; run scripts/extract_entity_physics.py")
    categories = data["categories"]

    lines: list[str] = []
    add = lines.append

    add("//! Every entity type the game has, and what each one is.")
    add("//!")
    add(f"//! Generated by `scripts/build_entity_types.py` from the {VERSION} data. Do not edit.")
    add("//!")
    add("//! The variants carry the registry's own numbers, so the value that goes on the wire is")
    add("//! the variant itself rather than something looked up beside it.")
    add("")
    add("pub use ferrumc_physics::Motion;")
    add("")

    # What a place has to be like before a mob appears there. Vanilla holds one of these per type
    # as a method reference; the ones more than one mob shares are named here and the rest are left
    # to the mob.
    add("/// What has to be true of a place before a mob appears there on its own.")
    add("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    add("pub enum SpawnRule {")
    add("    /// Nothing beyond where the kind may stand.")
    add("    None,")
    add("    /// Something a mob may stand on.")
    add("    Standable,")
    add("    /// Dark enough, and something to stand on.")
    add("    Dark,")
    add("    /// Something to stand on, however light it is.")
    add("    AnyLight,")
    add("    /// Dark enough, something to stand on, and open sky overhead.")
    add("    DarkUnderSky,")
    add("    /// Ground animals grow on, and bright enough to see.")
    add("    Animal,")
    add("    /// Water, near enough the surface.")
    add("    SurfaceWater,")
    add("    /// A rule of this mob's own. Nothing works one out yet, so a type carrying one never")
    add("    /// appears on its own rather than appearing where it should not.")
    add("    OwnRule,")
    add("}")
    add("")

    # The categories, in the order the game declares them.
    add("/// The group a type spawns and is counted in.")
    add("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    add("pub enum MobCategory {")
    for name in categories:
        add(f"    {variant(name)},")
    add("}")
    add("")
    add("/// What each category allows.")
    add("#[derive(Debug, Clone, Copy)]")
    add("pub struct CategoryDef {")
    add("    /// The name the data files use.")
    add("    pub name: &'static str,")
    add("    /// How many of this group may be in one chunk before no more spawn, or nothing")
    add("    /// where there is no limit.")
    add("    pub max_per_chunk: Option<u32>,")
    add("    /// Whether it counts as peaceful, which decides whether the difficulty removes it.")
    add("    pub friendly: bool,")
    add("    /// Whether one stays once spawned rather than despawning when nobody is near.")
    add("    pub persistent: bool,")
    add("    /// Past this many blocks from every player, one despawns at once.")
    add("    pub despawn_distance: u32,")
    add("    /// Within this many, one never despawns.")
    add("    pub no_despawn_distance: u32,")
    add("}")
    add("")
    add("impl MobCategory {")
    add("    /// The category of this name, as the packs write it.")
    add("    #[must_use]")
    add("    pub fn from_name(name: &str) -> Option<Self> {")
    add("        CATEGORIES")
    add("            .iter()")
    add("            .position(|def| def.name == name)")
    add("            .map(|index| ALL_CATEGORIES[index])")
    add("    }")
    add("")
    add("    /// Every category there is.")
    add("    #[must_use]")
    add("    pub const fn all() -> &'static [Self] {")
    add("        &ALL_CATEGORIES")
    add("    }")
    add("")
    add("    /// What this category allows.")
    add("    #[must_use]")
    add("    pub const fn def(self) -> &'static CategoryDef {")
    add("        &CATEGORIES[self as usize]")
    add("    }")
    add("}")
    add("")
    add("/// Every category, in the order the table holds them.")
    add(f"static ALL_CATEGORIES: [MobCategory; {len(categories)}] = [")
    for name in categories:
        add(f"    MobCategory::{variant(name)},")
    add("];")
    add("")
    add(f"static CATEGORIES: [CategoryDef; {len(categories)}] = [")
    for name, c in categories.items():
        add("    CategoryDef {")
        add(f'        name: "{name}",')
        limit = "None" if c["max_per_chunk"] < 0 else f"Some({c['max_per_chunk']})"
        add(f"        max_per_chunk: {limit},")
        add(f"        friendly: {str(c['friendly']).lower()},")
        add(f"        persistent: {str(c['persistent']).lower()},")
        add(f"        despawn_distance: {c['despawn_distance']},")
        add(f"        no_despawn_distance: {c['no_despawn_distance']},")
        add("    },")
    add("];")
    add("")

    add("/// Where a mob of a type may stand for it to spawn there.")
    add("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    add("pub enum SpawnPlacement {")
    add("    /// Anywhere at all.")
    add("    NoRestrictions,")
    add("    /// On a block that will hold it.")
    add("    OnGround,")
    add("    InWater,")
    add("    InLava,")
    add("}")
    add("")

    add("/// Which surface a spawn attempt is measured against.")
    add("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    add("pub enum SpawnHeightmap {")
    add("    MotionBlocking,")
    add("    MotionBlockingNoLeaves,")
    add("}")
    add("")

    add("/// What one entity type is.")
    add("#[derive(Debug, Clone, Copy)]")
    add("pub struct EntityDef {")
    add("    /// The name the registry gives it, namespace included.")
    add("    pub name: &'static str,")
    add("    pub category: MobCategory,")
    add("    /// How wide it is; an entity's box is square in plan.")
    add("    pub width: f32,")
    add("    pub height: f32,")
    add("    /// How far up the box it looks from.")
    add("    pub eye_height: f32,")
    add("    /// Whether the box stays this size whatever the entity is doing.")
    add("    pub fixed_size: bool,")
    add("    /// How many chunks away a client is still told about it.")
    add("    pub tracking_range: u8,")
    add("    /// How many ticks between updates, or nothing where it is never updated again.")
    add("    pub update_interval: Option<u32>,")
    add("    /// Whether it is written with the chunk it is in.")
    add("    pub serialize: bool,")
    add("    /// Whether a command may make one.")
    add("    pub summon: bool,")
    add("    pub fire_immune: bool,")
    add("    /// Whether it may spawn beyond the usual distance from a player.")
    add("    pub spawn_far_from_player: bool,")
    add("    /// Whether it survives the peaceful difficulty.")
    add("    pub allowed_in_peaceful: bool,")
    add("    pub placement: SpawnPlacement,")
    add("    pub heightmap: SpawnHeightmap,")
    add("    /// What a living one starts with, or nothing where it is not a living entity.")
    add("    pub max_health: Option<f32>,")
    add("    /// How a tick moves one of these when nothing else does.")
    add("    pub motion: Motion,")
    add("    /// What has to be true of a place before one appears there on its own.")
    add("    pub spawn_rule: SpawnRule,")
    add("}")
    add("")

    add("/// Every entity type, numbered as the registry numbers them.")
    add("///")
    add("/// This is the component an entity carries: there is nothing else to keep, since")
    add("/// everything the game says about a type is one index away from the variant.")
    add("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, bevy_ecs::prelude::Component)]")
    add("#[repr(u16)]")
    add("pub enum EntityType {")
    for t in types:
        add(f"    {variant(t['name'])} = {t['id']},")
    add("}")
    add("")

    add(f"/// One entry per type, in the order the variants are numbered.")
    add(f"pub(crate) static ENTITY_TYPES: [EntityDef; {len(types)}] = [")
    placements = {
        "no_restrictions": "NoRestrictions",
        "on_ground": "OnGround",
        "in_water": "InWater",
        "in_lava": "InLava",
    }
    heightmaps = {
        "MOTION_BLOCKING": "MotionBlocking",
        "MOTION_BLOCKING_NO_LEAVES": "MotionBlockingNoLeaves",
    }
    for t in types:
        interval = "None" if t["update_interval"] == NEVER else f"Some({t['update_interval']})"
        health = "None" if t["max_health"] is None else f"Some({rust_float(t['max_health'])})"
        add("    EntityDef {")
        add(f'        name: "{t["name"]}",')
        add(f"        category: MobCategory::{variant(t['category'])},")
        add(f"        width: {rust_float(t['width'])},")
        add(f"        height: {rust_float(t['height'])},")
        add(f"        eye_height: {rust_float(t['eye_height'])},")
        add(f"        fixed_size: {str(t['fixed_size']).lower()},")
        add(f"        tracking_range: {t['tracking_range']},")
        add(f"        update_interval: {interval},")
        add(f"        serialize: {str(t['serialize']).lower()},")
        add(f"        summon: {str(t['summon']).lower()},")
        add(f"        fire_immune: {str(t['fire_immune']).lower()},")
        add(f"        spawn_far_from_player: {str(t['spawn_far_from_player']).lower()},")
        add(f"        allowed_in_peaceful: {str(t['allowed_in_peaceful']).lower()},")
        add(f"        placement: SpawnPlacement::{placements[t['placement']]},")
        add(f"        heightmap: SpawnHeightmap::{heightmaps[t['heightmap']]},")
        add(f"        max_health: {health},")
        m = physics[t["name"]]
        add("        motion: Motion {")
        add(f"            gravity: {rust_float(m['gravity'])},")
        add(f"            air_drag: {rust_float(m['air_drag'])},")
        add(f"            step_height: {rust_float(m['step_height'])},")
        add(f"            living: {str(m['living']).lower()},")
        add(f"            omnidirectional: {str(m['omnidirectional']).lower()},")
        add(f"            pushed_by_fluid: {str(m['pushed_by_fluid']).lower()},")
        add("        },")
        rule = spawn_rules.get(t["name"])
        add(f"        spawn_rule: SpawnRule::{'None' if rule is None else SHARED_RULES.get(rule, 'OwnRule')},"
            + ("" if rule is None or rule in SHARED_RULES else f" // {rule}"))
        add("    },")
    add("];")
    add("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"{len(types)} entity types, {len(categories)} categories -> {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
