#!/usr/bin/env python3
"""Generate src/lib/world/src/block_tag/generated.rs from the vanilla block tags.

Tags are how vanilla groups blocks that share behaviour - every door, every block a sapling grows
on, everything a piston cannot push - and they are the grouping to register against. Matching on a
name pattern instead goes wrong the first time a block is named unlike its family.

Tags refer to other tags, so the references are resolved here and the generated lists are flat.

Usage:
    scripts/build_block_tags.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
NATIVE = "26.2"
TAG_DIR = REPO_ROOT / "assets" / "extracted" / NATIVE / "data" / "minecraft" / "tags" / "block"
BLOCK_REPORT = REPO_ROOT / "assets" / "extracted" / NATIVE / "reports" / "blocks.json"
OUT = REPO_ROOT / "src" / "lib" / "world" / "src" / "block_tag" / "generated.rs"


def resolve(name: str, seen: set[str] | None = None) -> set[str]:
    """Every block in a tag, with the tags it refers to folded in."""
    seen = set() if seen is None else seen
    if name in seen:
        return set()
    seen.add(name)

    path = TAG_DIR / f"{name.split(':')[-1]}.json"
    if not path.exists():
        return set()

    blocks = set()
    with path.open() as handle:
        for value in json.load(handle)["values"]:
            # An entry is either a name, a reference to another tag, or a name marked optional.
            entry = value["id"] if isinstance(value, dict) else value
            if entry.startswith("#"):
                blocks |= resolve(entry[1:], seen)
            else:
                blocks.add(entry)
    return blocks


def main() -> None:
    with BLOCK_REPORT.open() as handle:
        report = json.load(handle)
    order = sorted(
        report, key=lambda name: min(state["id"] for state in report[name]["states"])
    )
    index = {name: position for position, name in enumerate(order)}

    tags = {}
    for path in sorted(TAG_DIR.glob("*.json")):
        name = f"minecraft:{path.stem}"
        # A tag may name blocks a version does not have; those are optional entries and are dropped.
        blocks = sorted(index[block] for block in resolve(name) if block in index)
        tags[name] = blocks

    lines = [
        "//! Which blocks each vanilla tag holds.",
        "//!",
        "//! Generated by `scripts/build_block_tags.py`. References between tags are already",
        "//! resolved, so every list is flat. Do not edit.",
        "",
        "/// A tag, as indices into the block table.",
        "pub struct BlockTag {",
        "    pub name: &'static str,",
        "    pub blocks: &'static [u16],",
        "}",
        "",
        "/// Sorted by name, so a lookup is a binary search.",
        f"pub static TAGS: [BlockTag; {len(tags)}] = [",
    ]
    for name, blocks in sorted(tags.items()):
        rendered = ", ".join(str(block) for block in blocks)
        lines.append(f'    BlockTag {{ name: "{name}", blocks: &[{rendered}] }},')
    lines += ["];", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    total = sum(len(blocks) for blocks in tags.values())
    print(f"{len(tags)} tags, {total} memberships -> {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
