//! Which blocks each vanilla tag holds.
//!
//! Generated by `scripts/build_block_tags.py`. References between tags are already
//! resolved, so every list is flat. Do not edit.

/// A tag, as indices into the block table.
pub struct BlockTag {
    pub name: &'static str,
    pub blocks: &'static [u16],
}

/// Sorted by name, so a lookup is a binary search.
pub static TAGS: [BlockTag; 261] = [
    BlockTag {
        name: "minecraft:acacia_logs",
        blocks: &[53, 64, 75, 83],
    },
    BlockTag {
        name: "minecraft:air",
        blocks: &[0, 794, 795],
    },
    BlockTag {
        name: "minecraft:all_hanging_signs",
        blocks: &[
            234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250,
            251, 252, 253, 254, 255, 256, 257,
        ],
    },
    BlockTag {
        name: "minecraft:all_signs",
        blocks: &[
            210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 224, 225, 226, 227, 228, 229, 230,
            231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
            248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 901, 902, 903, 904,
        ],
    },
    BlockTag {
        name: "minecraft:ancient_city_replaceable",
        blocks: &[
            147, 1151, 1152, 1160, 1162, 1163, 1164, 1165, 1166, 1167, 1169, 1170,
        ],
    },
    BlockTag {
        name: "minecraft:animals_spawnable_on",
        blocks: &[8],
    },
    BlockTag {
        name: "minecraft:anvil",
        blocks: &[467, 468, 469],
    },
    BlockTag {
        name: "minecraft:armadillo_spawnable_on",
        blocks: &[8, 10, 39, 484, 485, 488, 492, 496, 498, 554],
    },
    BlockTag {
        name: "minecraft:axolotls_spawnable_on",
        blocks: &[281],
    },
    BlockTag {
        name: "minecraft:azalea_grows_on",
        blocks: &[
            8, 9, 10, 11, 37, 38, 39, 59, 278, 373, 484, 485, 486, 487, 488, 489, 490, 491, 492,
            493, 494, 495, 496, 497, 498, 499, 554, 1027, 1144, 1149, 1150, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:azalea_root_replaceable",
        blocks: &[
            1, 2, 4, 6, 8, 9, 10, 11, 37, 39, 40, 59, 278, 281, 373, 484, 485, 486, 487, 488, 489,
            490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 554, 984, 1027, 1144, 1149, 1150,
            1151, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:badlands_terracotta",
        blocks: &[484, 485, 488, 492, 496, 498, 554],
    },
    BlockTag {
        name: "minecraft:bamboo_blocks",
        blocks: &[60, 70],
    },
    BlockTag {
        name: "minecraft:banners",
        blocks: &[
            563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579,
            580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594,
        ],
    },
    BlockTag {
        name: "minecraft:bars",
        blocks: &[341, 342, 343, 344, 345, 346, 347, 348, 349],
    },
    BlockTag {
        name: "minecraft:base_stone_nether",
        blocks: &[285, 288, 924],
    },
    BlockTag {
        name: "minecraft:base_stone_overworld",
        blocks: &[1, 2, 4, 6, 984, 1151],
    },
    BlockTag {
        name: "minecraft:bats_spawnable_on",
        blocks: &[1, 2, 4, 6, 984, 1151],
    },
    BlockTag {
        name: "minecraft:beacon_base_blocks",
        blocks: &[174, 175, 205, 403, 915],
    },
    BlockTag {
        name: "minecraft:beds",
        blocks: &[
            110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        ],
    },
    BlockTag {
        name: "minecraft:bee_attractive",
        blocks: &[
            33, 93, 98, 157, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 280,
            557, 558, 559, 560, 657, 664, 1137, 1139, 1141, 1142, 1191,
        ],
    },
    BlockTag {
        name: "minecraft:bee_growables",
        blocks: &[207, 364, 365, 441, 442, 662, 663, 665, 861, 1135, 1136],
    },
    BlockTag {
        name: "minecraft:beehives",
        blocks: &[911, 912],
    },
    BlockTag {
        name: "minecraft:beneath_bamboo_podzol_replaceable",
        blocks: &[8, 9, 10, 11, 59, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:beneath_tree_podzol_replaceable",
        blocks: &[8, 9, 10, 11, 59, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:birch_logs",
        blocks: &[51, 62, 73, 81],
    },
    BlockTag {
        name: "minecraft:blocks_wind_charge_explosions",
        blocks: &[34, 524],
    },
    BlockTag {
        name: "minecraft:buttons",
        blocks: &[
            275, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 897, 898, 939,
        ],
    },
    BlockTag {
        name: "minecraft:camel_sand_step_sound_blocks",
        blocks: &[
            37, 38, 39, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
            741,
        ],
    },
    BlockTag {
        name: "minecraft:camels_spawnable_on",
        blocks: &[37, 38, 39],
    },
    BlockTag {
        name: "minecraft:campfires",
        blocks: &[859, 860],
    },
    BlockTag {
        name: "minecraft:can_glide_through",
        blocks: &[366, 878, 879, 880, 881, 1135, 1136],
    },
    BlockTag {
        name: "minecraft:candle_cakes",
        blocks: &[
            961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977,
        ],
    },
    BlockTag {
        name: "minecraft:candles",
        blocks: &[
            944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960,
        ],
    },
    BlockTag {
        name: "minecraft:cannot_replace_below_tree_trunk",
        blocks: &[9, 10, 11, 59, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:cannot_support_kelp",
        blocks: &[671],
    },
    BlockTag {
        name: "minecraft:cannot_support_seagrass",
        blocks: &[671],
    },
    BlockTag {
        name: "minecraft:cannot_support_snow_layer",
        blocks: &[277, 524, 556],
    },
    BlockTag {
        name: "minecraft:cauldrons",
        blocks: &[387, 388, 389, 390],
    },
    BlockTag {
        name: "minecraft:causes_continuous_geyser_eruptions",
        blocks: &[36],
    },
    BlockTag {
        name: "minecraft:causes_periodic_geyser_eruptions",
        blocks: &[671],
    },
    BlockTag {
        name: "minecraft:cave_vines",
        blocks: &[1135, 1136],
    },
    BlockTag {
        name: "minecraft:ceiling_hanging_signs",
        blocks: &[234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245],
    },
    BlockTag {
        name: "minecraft:chains",
        blocks: &[350, 351, 352, 353, 354, 355, 356, 357, 358],
    },
    BlockTag {
        name: "minecraft:cherry_logs",
        blocks: &[54, 65, 76, 84],
    },
    BlockTag {
        name: "minecraft:climbable",
        blocks: &[221, 366, 837, 878, 879, 880, 881, 1135, 1136],
    },
    BlockTag {
        name: "minecraft:coal_ores",
        blocks: &[46, 47],
    },
    BlockTag {
        name: "minecraft:combination_step_sound_blocks",
        blocks: &[
            276, 368, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
            553, 869, 870, 882, 1140, 1189,
        ],
    },
    BlockTag {
        name: "minecraft:completes_find_tree_tutorial",
        blocks: &[
            20, 49, 50, 51, 52, 53, 54, 55, 56, 57, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73,
            74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
            96, 97, 98, 672, 862, 863, 864, 865, 868, 871, 872, 873, 874,
        ],
    },
    BlockTag {
        name: "minecraft:concrete",
        blocks: &[
            710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725,
        ],
    },
    BlockTag {
        name: "minecraft:concrete_powders",
        blocks: &[
            726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741,
        ],
    },
    BlockTag {
        name: "minecraft:convertable_to_mud",
        blocks: &[9, 10, 1149],
    },
    BlockTag {
        name: "minecraft:copper",
        blocks: &[1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041],
    },
    BlockTag {
        name: "minecraft:copper_chests",
        blocks: &[1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115],
    },
    BlockTag {
        name: "minecraft:copper_golem_statues",
        blocks: &[1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123],
    },
    BlockTag {
        name: "minecraft:copper_ores",
        blocks: &[1042, 1043],
    },
    BlockTag {
        name: "minecraft:coral_blocks",
        blocks: &[753, 754, 755, 756, 757],
    },
    BlockTag {
        name: "minecraft:coral_plants",
        blocks: &[763, 764, 765, 766, 767],
    },
    BlockTag {
        name: "minecraft:corals",
        blocks: &[763, 764, 765, 766, 767, 773, 774, 775, 776, 777],
    },
    BlockTag {
        name: "minecraft:crimson_stems",
        blocks: &[871, 872, 873, 874],
    },
    BlockTag {
        name: "minecraft:crops",
        blocks: &[207, 364, 365, 441, 442, 662, 663, 665],
    },
    BlockTag {
        name: "minecraft:crystal_sound_blocks",
        blocks: &[978, 979],
    },
    BlockTag {
        name: "minecraft:dampens_vibrations",
        blocks: &[
            140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 538,
            539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553,
        ],
    },
    BlockTag {
        name: "minecraft:dark_oak_logs",
        blocks: &[55, 66, 77, 85],
    },
    BlockTag {
        name: "minecraft:deepslate_ore_replaceables",
        blocks: &[984, 1151],
    },
    BlockTag {
        name: "minecraft:default_immune_to",
        blocks: &[],
    },
    BlockTag {
        name: "minecraft:diamond_ores",
        blocks: &[203, 204],
    },
    BlockTag {
        name: "minecraft:dirt",
        blocks: &[9, 10, 1149],
    },
    BlockTag {
        name: "minecraft:does_not_block_hoppers",
        blocks: &[911, 912],
    },
    BlockTag {
        name: "minecraft:doors",
        blocks: &[
            220, 260, 646, 647, 648, 649, 650, 651, 652, 653, 654, 899, 900, 1076, 1077, 1078,
            1079, 1080, 1081, 1082, 1083,
        ],
    },
    BlockTag {
        name: "minecraft:dragon_immune",
        blocks: &[
            34, 156, 193, 341, 391, 392, 393, 407, 524, 667, 668, 669, 905, 906, 907, 908, 917,
            918, 1182,
        ],
    },
    BlockTag {
        name: "minecraft:dragon_transparent",
        blocks: &[196, 197, 525],
    },
    BlockTag {
        name: "minecraft:dripstone_replaceable_blocks",
        blocks: &[1, 2, 4, 6, 984, 1151],
    },
    BlockTag {
        name: "minecraft:edible_for_sheep",
        blocks: &[130, 131, 134, 135],
    },
    BlockTag {
        name: "minecraft:emerald_ores",
        blocks: &[398, 399],
    },
    BlockTag {
        name: "minecraft:enables_bubble_column_drag_down",
        blocks: &[671],
    },
    BlockTag {
        name: "minecraft:enables_bubble_column_push_up",
        blocks: &[286],
    },
    BlockTag {
        name: "minecraft:enchantment_power_provider",
        blocks: &[178],
    },
    BlockTag {
        name: "minecraft:enchantment_power_transmitter",
        blocks: &[
            0, 35, 36, 130, 131, 132, 133, 134, 135, 136, 137, 196, 197, 276, 366, 367, 368, 525,
            561, 562, 675, 794, 795, 796, 869, 870, 882, 1143, 1148,
        ],
    },
    BlockTag {
        name: "minecraft:enderman_holdable",
        blocks: &[
            8, 9, 10, 11, 37, 39, 40, 59, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
            168, 169, 170, 171, 172, 173, 177, 279, 280, 281, 296, 360, 361, 373, 866, 867, 869,
            875, 876, 882, 1144, 1149, 1150, 1188, 1191, 1192,
        ],
    },
    BlockTag {
        name: "minecraft:fall_damage_resetting",
        blocks: &[129, 221, 366, 837, 861, 878, 879, 880, 881, 1135, 1136],
    },
    BlockTag {
        name: "minecraft:features_cannot_replace",
        blocks: &[34, 198, 201, 392, 1182, 1185, 1186],
    },
    BlockTag {
        name: "minecraft:fence_gates",
        blocks: &[369, 628, 629, 630, 631, 632, 633, 634, 635, 636, 893, 894],
    },
    BlockTag {
        name: "minecraft:fences",
        blocks: &[
            284, 382, 637, 638, 639, 640, 641, 642, 643, 644, 645, 889, 890,
        ],
    },
    BlockTag {
        name: "minecraft:fire",
        blocks: &[196, 197],
    },
    BlockTag {
        name: "minecraft:flower_pots",
        blocks: &[
            411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427,
            428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 793, 919, 920, 921,
            922, 1176, 1177, 1193, 1194,
        ],
    },
    BlockTag {
        name: "minecraft:flowers",
        blocks: &[
            33, 93, 98, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
            280, 557, 558, 559, 560, 657, 664, 1137, 1139, 1141, 1142, 1191, 1192,
        ],
    },
    BlockTag {
        name: "minecraft:forest_rock_can_place_on",
        blocks: &[
            1, 2, 4, 6, 8, 9, 10, 11, 59, 373, 984, 1144, 1149, 1150, 1151, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:fox_immune_to",
        blocks: &[861],
    },
    BlockTag {
        name: "minecraft:foxes_spawnable_on",
        blocks: &[8, 10, 11, 276, 278],
    },
    BlockTag {
        name: "minecraft:frog_prefer_jump_to",
        blocks: &[374, 1145],
    },
    BlockTag {
        name: "minecraft:frogs_spawnable_on",
        blocks: &[8, 58, 59, 1150],
    },
    BlockTag {
        name: "minecraft:geode_invalid_blocks",
        blocks: &[34, 35, 36, 277, 556, 789],
    },
    BlockTag {
        name: "minecraft:glazed_terracotta",
        blocks: &[
            694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709,
        ],
    },
    BlockTag {
        name: "minecraft:goats_spawnable_on",
        blocks: &[1, 8, 40, 276, 278, 556],
    },
    BlockTag {
        name: "minecraft:gold_ores",
        blocks: &[42, 43, 48],
    },
    BlockTag {
        name: "minecraft:grass_blocks",
        blocks: &[8, 11, 373],
    },
    BlockTag {
        name: "minecraft:grows_crops",
        blocks: &[208],
    },
    BlockTag {
        name: "minecraft:guarded_by_piglins",
        blocks: &[
            42, 43, 48, 174, 201, 400, 470, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687,
            688, 689, 690, 691, 692, 693, 839, 935, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115,
            1175,
        ],
    },
    BlockTag {
        name: "minecraft:happy_ghast_avoids",
        blocks: &[170, 196, 279, 671, 861, 1133, 1134],
    },
    BlockTag {
        name: "minecraft:hoglin_repellents",
        blocks: &[295, 867, 918, 920],
    },
    BlockTag {
        name: "minecraft:huge_brown_mushroom_can_place_on",
        blocks: &[8, 9, 10, 11, 59, 373, 866, 875, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:huge_red_mushroom_can_place_on",
        blocks: &[8, 9, 10, 11, 59, 373, 866, 875, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:ice",
        blocks: &[277, 556, 670, 789],
    },
    BlockTag {
        name: "minecraft:ice_spike_replaceable",
        blocks: &[8, 9, 10, 11, 59, 277, 278, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:impermeable",
        blocks: &[
            101, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315,
            524, 1026,
        ],
    },
    BlockTag {
        name: "minecraft:incorrect_for_copper_tool",
        blocks: &[
            42, 43, 174, 193, 203, 204, 205, 271, 272, 398, 399, 403, 915, 916, 917, 918, 1175,
        ],
    },
    BlockTag {
        name: "minecraft:incorrect_for_diamond_tool",
        blocks: &[],
    },
    BlockTag {
        name: "minecraft:incorrect_for_gold_tool",
        blocks: &[
            42, 43, 44, 45, 102, 103, 104, 174, 175, 193, 203, 204, 205, 271, 272, 398, 399, 403,
            915, 916, 917, 918, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044,
            1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058,
            1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072,
            1073, 1074, 1075, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094,
            1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108,
            1109, 1110, 1111, 1112, 1113, 1114, 1115, 1124, 1125, 1126, 1127, 1128, 1129, 1130,
            1131, 1173, 1174, 1175, 1184,
        ],
    },
    BlockTag {
        name: "minecraft:incorrect_for_iron_tool",
        blocks: &[193, 915, 916, 917, 918],
    },
    BlockTag {
        name: "minecraft:incorrect_for_netherite_tool",
        blocks: &[],
    },
    BlockTag {
        name: "minecraft:incorrect_for_stone_tool",
        blocks: &[
            42, 43, 174, 193, 203, 204, 205, 271, 272, 398, 399, 403, 915, 916, 917, 918, 1175,
        ],
    },
    BlockTag {
        name: "minecraft:incorrect_for_wooden_tool",
        blocks: &[
            42, 43, 44, 45, 102, 103, 104, 174, 175, 193, 203, 204, 205, 271, 272, 398, 399, 403,
            915, 916, 917, 918, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044,
            1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058,
            1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072,
            1073, 1074, 1075, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094,
            1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108,
            1109, 1110, 1111, 1112, 1113, 1114, 1115, 1124, 1125, 1126, 1127, 1128, 1129, 1130,
            1131, 1173, 1174, 1175, 1184,
        ],
    },
    BlockTag {
        name: "minecraft:infiniburn_end",
        blocks: &[34, 285, 671],
    },
    BlockTag {
        name: "minecraft:infiniburn_nether",
        blocks: &[285, 671],
    },
    BlockTag {
        name: "minecraft:infiniburn_overworld",
        blocks: &[285, 671],
    },
    BlockTag {
        name: "minecraft:inside_step_sound_blocks",
        blocks: &[367, 374, 983, 1027, 1031, 1141, 1142, 1143],
    },
    BlockTag {
        name: "minecraft:invalid_spawn_inside",
        blocks: &[391, 667],
    },
    BlockTag {
        name: "minecraft:iron_ores",
        blocks: &[44, 45],
    },
    BlockTag {
        name: "minecraft:jungle_logs",
        blocks: &[52, 63, 74, 82],
    },
    BlockTag {
        name: "minecraft:lanterns",
        blocks: &[849, 850, 851, 852, 853, 854, 855, 856, 857, 858],
    },
    BlockTag {
        name: "minecraft:lapis_ores",
        blocks: &[102, 103],
    },
    BlockTag {
        name: "minecraft:lava_pool_stone_cannot_replace",
        blocks: &[
            20, 34, 49, 50, 51, 52, 53, 54, 55, 56, 57, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72,
            73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
            95, 96, 97, 98, 198, 201, 392, 862, 863, 864, 865, 871, 872, 873, 874, 1182, 1185,
            1186,
        ],
    },
    BlockTag {
        name: "minecraft:leaves",
        blocks: &[88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98],
    },
    BlockTag {
        name: "minecraft:lightning_rods",
        blocks: &[1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131],
    },
    BlockTag {
        name: "minecraft:logs",
        blocks: &[
            20, 49, 50, 51, 52, 53, 54, 55, 56, 57, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73,
            74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 862, 863, 864, 865, 871, 872,
            873, 874,
        ],
    },
    BlockTag {
        name: "minecraft:logs_that_burn",
        blocks: &[
            20, 49, 50, 51, 52, 53, 54, 55, 56, 57, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73,
            74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
        ],
    },
    BlockTag {
        name: "minecraft:lush_ground_replaceable",
        blocks: &[
            1, 2, 4, 6, 8, 9, 10, 11, 37, 40, 59, 281, 373, 984, 1135, 1136, 1144, 1149, 1150,
            1151, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:maintains_farmland",
        blocks: &[
            156, 159, 207, 362, 363, 364, 365, 369, 441, 442, 628, 629, 630, 631, 632, 633, 634,
            635, 636, 662, 663, 665, 893, 894,
        ],
    },
    BlockTag {
        name: "minecraft:mangrove_logs",
        blocks: &[57, 69, 78, 87],
    },
    BlockTag {
        name: "minecraft:mangrove_logs_can_grow_through",
        blocks: &[33, 57, 58, 59, 96, 366, 1140, 1150],
    },
    BlockTag {
        name: "minecraft:mangrove_roots_can_grow_through",
        blocks: &[33, 58, 59, 276, 366, 1140, 1150],
    },
    BlockTag {
        name: "minecraft:mob_interactable_doors",
        blocks: &[
            220, 646, 647, 648, 649, 650, 651, 652, 653, 654, 899, 900, 1076, 1077, 1078, 1079,
            1080, 1081, 1082, 1083,
        ],
    },
    BlockTag {
        name: "minecraft:mooshrooms_spawnable_on",
        blocks: &[373],
    },
    BlockTag {
        name: "minecraft:moss_blocks",
        blocks: &[1144, 1188],
    },
    BlockTag {
        name: "minecraft:moss_replaceable",
        blocks: &[
            1, 2, 4, 6, 8, 9, 10, 11, 59, 373, 984, 1135, 1136, 1144, 1149, 1150, 1151, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:mud",
        blocks: &[59, 1150],
    },
    BlockTag {
        name: "minecraft:needs_diamond_tool",
        blocks: &[193, 915, 916, 917, 918],
    },
    BlockTag {
        name: "minecraft:needs_iron_tool",
        blocks: &[42, 43, 174, 203, 204, 205, 271, 272, 398, 399, 403, 1175],
    },
    BlockTag {
        name: "minecraft:needs_stone_tool",
        blocks: &[
            44, 45, 102, 103, 104, 175, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043,
            1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057,
            1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071,
            1072, 1073, 1074, 1075, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093,
            1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107,
            1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1124, 1125, 1126, 1127, 1128, 1129,
            1130, 1131, 1173, 1174, 1184,
        ],
    },
    BlockTag {
        name: "minecraft:nether_carver_replaceables",
        blocks: &[
            1, 2, 4, 6, 8, 9, 10, 11, 59, 285, 286, 287, 288, 373, 672, 866, 868, 875, 924, 984,
            1144, 1149, 1150, 1151, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:nylium",
        blocks: &[866, 875],
    },
    BlockTag {
        name: "minecraft:oak_logs",
        blocks: &[49, 68, 71, 79],
    },
    BlockTag {
        name: "minecraft:occludes_vibration_signals",
        blocks: &[
            140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        ],
    },
    BlockTag {
        name: "minecraft:overrides_mushroom_light_requirement",
        blocks: &[11, 373, 866, 875],
    },
    BlockTag {
        name: "minecraft:overworld_carver_replaceables",
        blocks: &[
            1, 2, 4, 6, 8, 9, 10, 11, 35, 37, 38, 39, 40, 41, 44, 45, 59, 106, 276, 278, 373, 484,
            485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 554, 556,
            595, 984, 998, 999, 1012, 1025, 1027, 1042, 1043, 1144, 1149, 1150, 1151, 1173, 1174,
            1188,
        ],
    },
    BlockTag {
        name: "minecraft:overworld_natural_logs",
        blocks: &[49, 50, 51, 52, 53, 54, 55, 56, 57],
    },
    BlockTag {
        name: "minecraft:pale_oak_logs",
        blocks: &[20, 56, 67, 86],
    },
    BlockTag {
        name: "minecraft:parrots_spawnable_on",
        blocks: &[
            0, 8, 20, 49, 50, 51, 52, 53, 54, 55, 56, 57, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71,
            72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
            94, 95, 96, 97, 98, 862, 863, 864, 865, 871, 872, 873, 874,
        ],
    },
    BlockTag {
        name: "minecraft:piglin_repellents",
        blocks: &[197, 290, 291, 850, 860],
    },
    BlockTag {
        name: "minecraft:planks",
        blocks: &[13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 883, 884],
    },
    BlockTag {
        name: "minecraft:polar_bear_immune_to",
        blocks: &[1027],
    },
    BlockTag {
        name: "minecraft:polar_bears_spawnable_on_alternate",
        blocks: &[277],
    },
    BlockTag {
        name: "minecraft:portals",
        blocks: &[295, 391, 667],
    },
    BlockTag {
        name: "minecraft:pressure_plates",
        blocks: &[
            259, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 471, 472, 887, 888, 938,
        ],
    },
    BlockTag {
        name: "minecraft:prevent_mob_spawning_inside",
        blocks: &[126, 127, 222, 482],
    },
    BlockTag {
        name: "minecraft:prevents_nearby_leaf_decay",
        blocks: &[
            20, 49, 50, 51, 52, 53, 54, 55, 56, 57, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73,
            74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 862, 863, 864, 865, 871, 872,
            873, 874,
        ],
    },
    BlockTag {
        name: "minecraft:rabbits_spawnable_on",
        blocks: &[8, 37, 276, 278],
    },
    BlockTag {
        name: "minecraft:rails",
        blocks: &[126, 127, 222, 482],
    },
    BlockTag {
        name: "minecraft:redstone_ores",
        blocks: &[271, 272],
    },
    BlockTag {
        name: "minecraft:replaceable",
        blocks: &[
            0, 35, 36, 130, 131, 132, 133, 134, 135, 136, 137, 196, 197, 276, 366, 367, 368, 525,
            561, 562, 675, 794, 795, 796, 869, 870, 882, 1143, 1148,
        ],
    },
    BlockTag {
        name: "minecraft:replaceable_by_mushrooms",
        blocks: &[
            35, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 130, 131, 132, 133, 134, 135, 136, 137,
            157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173,
            338, 339, 366, 367, 557, 558, 559, 560, 561, 562, 664, 869, 870, 882, 1143, 1148, 1189,
            1191, 1192, 1195,
        ],
    },
    BlockTag {
        name: "minecraft:replaceable_by_trees",
        blocks: &[
            35, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 130, 131, 132, 133, 134, 135, 136, 137,
            157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 366, 367,
            557, 558, 559, 560, 561, 562, 664, 869, 870, 882, 1143, 1148, 1189, 1191, 1192, 1195,
        ],
    },
    BlockTag {
        name: "minecraft:sand",
        blocks: &[37, 38, 39],
    },
    BlockTag {
        name: "minecraft:saplings",
        blocks: &[25, 26, 27, 28, 29, 30, 31, 32, 33, 1138, 1139],
    },
    BlockTag {
        name: "minecraft:sculk_replaceable",
        blocks: &[
            1, 2, 4, 6, 8, 9, 10, 11, 37, 39, 40, 59, 106, 281, 285, 286, 287, 288, 373, 393, 484,
            485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 554, 595,
            866, 875, 924, 984, 998, 1012, 1025, 1132, 1144, 1149, 1150, 1151, 1172, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:sculk_replaceable_world_gen",
        blocks: &[
            1, 2, 4, 6, 8, 9, 10, 11, 37, 39, 40, 59, 106, 281, 285, 286, 287, 288, 373, 393, 484,
            485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 554, 595,
            866, 875, 924, 984, 998, 1012, 1025, 1132, 1144, 1149, 1150, 1151, 1152, 1156, 1160,
            1164, 1169, 1170, 1172, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:shears_extreme_breaking_speed",
        blocks: &[88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98],
    },
    BlockTag {
        name: "minecraft:shears_major_breaking_speed",
        blocks: &[
            140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        ],
    },
    BlockTag {
        name: "minecraft:shears_minor_breaking_speed",
        blocks: &[366, 367],
    },
    BlockTag {
        name: "minecraft:shulker_boxes",
        blocks: &[
            677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693,
        ],
    },
    BlockTag {
        name: "minecraft:signs",
        blocks: &[
            210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 224, 225, 226, 227, 228, 229, 230,
            231, 232, 233, 901, 902, 903, 904,
        ],
    },
    BlockTag {
        name: "minecraft:slabs",
        blocks: &[
            378, 533, 534, 535, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611,
            612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 811, 812, 813, 814, 815,
            816, 817, 818, 819, 820, 821, 822, 823, 885, 886, 927, 932, 937, 985, 989, 994, 1000,
            1004, 1008, 1013, 1017, 1021, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1154,
            1158, 1162, 1166,
        ],
    },
    BlockTag {
        name: "minecraft:small_flowers",
        blocks: &[
            157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 1191, 1192,
        ],
    },
    BlockTag {
        name: "minecraft:smelts_to_glass",
        blocks: &[37, 39],
    },
    BlockTag {
        name: "minecraft:snaps_goat_horn",
        blocks: &[
            1, 44, 46, 49, 50, 51, 52, 53, 54, 55, 56, 57, 398, 556, 1042,
        ],
    },
    BlockTag {
        name: "minecraft:sniffer_diggable_block",
        blocks: &[8, 9, 10, 11, 59, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:sniffer_egg_hatch_boost",
        blocks: &[1144],
    },
    BlockTag {
        name: "minecraft:snow",
        blocks: &[276, 278, 1027],
    },
    BlockTag {
        name: "minecraft:snow_golem_immune_to",
        blocks: &[1027],
    },
    BlockTag {
        name: "minecraft:soul_fire_base_blocks",
        blocks: &[286, 287],
    },
    BlockTag {
        name: "minecraft:soul_speed_blocks",
        blocks: &[286, 287],
    },
    BlockTag {
        name: "minecraft:speleothems",
        blocks: &[1133, 1134],
    },
    BlockTag {
        name: "minecraft:spruce_logs",
        blocks: &[50, 61, 72, 80],
    },
    BlockTag {
        name: "minecraft:stairs",
        blocks: &[
            200, 223, 370, 371, 372, 377, 383, 397, 404, 405, 406, 481, 516, 517, 518, 519, 520,
            521, 522, 530, 531, 532, 598, 660, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806,
            807, 808, 809, 810, 895, 896, 925, 933, 936, 986, 990, 995, 1001, 1005, 1009, 1014,
            1018, 1022, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1153, 1157, 1161, 1165,
        ],
    },
    BlockTag {
        name: "minecraft:standing_signs",
        blocks: &[210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 901, 902],
    },
    BlockTag {
        name: "minecraft:stone_bricks",
        blocks: &[326, 327, 328, 329],
    },
    BlockTag {
        name: "minecraft:stone_buttons",
        blocks: &[275, 939],
    },
    BlockTag {
        name: "minecraft:stone_ore_replaceables",
        blocks: &[1, 2, 4, 6],
    },
    BlockTag {
        name: "minecraft:stone_pressure_plates",
        blocks: &[259, 938],
    },
    BlockTag {
        name: "minecraft:stray_immune_to",
        blocks: &[1027],
    },
    BlockTag {
        name: "minecraft:strider_warm_blocks",
        blocks: &[36],
    },
    BlockTag {
        name: "minecraft:substrate_overworld",
        blocks: &[8, 9, 10, 11, 59, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:sulfur_spike_replaceable_blocks",
        blocks: &[998, 1012],
    },
    BlockTag {
        name: "minecraft:support_override_cactus_flower",
        blocks: &[208, 279],
    },
    BlockTag {
        name: "minecraft:support_override_snow_layer",
        blocks: &[286, 913, 1150],
    },
    BlockTag {
        name: "minecraft:supports_azalea",
        blocks: &[8, 9, 10, 11, 59, 208, 281, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:supports_bamboo",
        blocks: &[
            8, 9, 10, 11, 37, 38, 39, 40, 41, 59, 373, 791, 792, 1144, 1149, 1150, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:supports_big_dripleaf",
        blocks: &[8, 9, 10, 11, 59, 208, 281, 373, 1144, 1149, 1150],
    },
    BlockTag {
        name: "minecraft:supports_cactus",
        blocks: &[37, 38, 39],
    },
    BlockTag {
        name: "minecraft:supports_chorus_flower",
        blocks: &[393],
    },
    BlockTag {
        name: "minecraft:supports_chorus_plant",
        blocks: &[393],
    },
    BlockTag {
        name: "minecraft:supports_cocoa",
        blocks: &[52, 63, 74, 82],
    },
    BlockTag {
        name: "minecraft:supports_crimson_fungus",
        blocks: &[
            8, 9, 10, 11, 59, 208, 287, 373, 866, 875, 1144, 1149, 1150, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:supports_crimson_roots",
        blocks: &[
            8, 9, 10, 11, 59, 208, 287, 373, 866, 875, 1144, 1149, 1150, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:supports_crops",
        blocks: &[208],
    },
    BlockTag {
        name: "minecraft:supports_dry_vegetation",
        blocks: &[
            8, 9, 10, 11, 37, 38, 39, 59, 208, 373, 484, 485, 486, 487, 488, 489, 490, 491, 492,
            493, 494, 495, 496, 497, 498, 499, 554, 1144, 1149, 1150, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:supports_frogspawn",
        blocks: &[],
    },
    BlockTag {
        name: "minecraft:supports_hanging_mangrove_propagule",
        blocks: &[96],
    },
    BlockTag {
        name: "minecraft:supports_lily_pad",
        blocks: &[277, 670],
    },
    BlockTag {
        name: "minecraft:supports_mangrove_propagule",
        blocks: &[8, 9, 10, 11, 59, 208, 281, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:supports_melon_stem",
        blocks: &[208],
    },
    BlockTag {
        name: "minecraft:supports_melon_stem_fruit",
        blocks: &[8, 9, 10, 11, 59, 208, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:supports_nether_sprouts",
        blocks: &[
            8, 9, 10, 11, 59, 208, 287, 373, 866, 875, 1144, 1149, 1150, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:supports_nether_wart",
        blocks: &[286],
    },
    BlockTag {
        name: "minecraft:supports_pumpkin_stem",
        blocks: &[208],
    },
    BlockTag {
        name: "minecraft:supports_pumpkin_stem_fruit",
        blocks: &[8, 9, 10, 11, 59, 208, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:supports_small_dripleaf",
        blocks: &[281, 1144],
    },
    BlockTag {
        name: "minecraft:supports_stem_crops",
        blocks: &[208],
    },
    BlockTag {
        name: "minecraft:supports_stem_fruit",
        blocks: &[8, 9, 10, 11, 59, 208, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:supports_sugar_cane",
        blocks: &[8, 9, 10, 11, 37, 38, 39, 59, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:supports_sugar_cane_adjacently",
        blocks: &[670],
    },
    BlockTag {
        name: "minecraft:supports_vegetation",
        blocks: &[8, 9, 10, 11, 59, 208, 373, 1144, 1149, 1150, 1188],
    },
    BlockTag {
        name: "minecraft:supports_warped_fungus",
        blocks: &[
            8, 9, 10, 11, 59, 208, 287, 373, 866, 875, 1144, 1149, 1150, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:supports_warped_roots",
        blocks: &[
            8, 9, 10, 11, 59, 208, 287, 373, 866, 875, 1144, 1149, 1150, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:supports_wither_rose",
        blocks: &[
            8, 9, 10, 11, 59, 208, 285, 286, 287, 373, 1144, 1149, 1150, 1188,
        ],
    },
    BlockTag {
        name: "minecraft:suppresses_bounce",
        blocks: &[913],
    },
    BlockTag {
        name: "minecraft:sword_efficient",
        blocks: &[
            88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 296, 297, 360, 361, 366, 367, 396, 656,
            657, 1145, 1146,
        ],
    },
    BlockTag {
        name: "minecraft:sword_instantly_mines",
        blocks: &[791, 792],
    },
    BlockTag {
        name: "minecraft:terracotta",
        blocks: &[
            484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 554,
        ],
    },
    BlockTag {
        name: "minecraft:trail_ruins_replaceable",
        blocks: &[40],
    },
    BlockTag {
        name: "minecraft:trapdoors",
        blocks: &[
            316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 526, 891, 892, 1084, 1085, 1086,
            1087, 1088, 1089, 1090, 1091,
        ],
    },
    BlockTag {
        name: "minecraft:triggers_ambient_desert_dry_vegetation_block_sounds",
        blocks: &[
            37, 39, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499,
            554,
        ],
    },
    BlockTag {
        name: "minecraft:triggers_ambient_desert_sand_block_sounds",
        blocks: &[37, 39],
    },
    BlockTag {
        name: "minecraft:triggers_ambient_dried_ghast_block_sounds",
        blocks: &[286, 287],
    },
    BlockTag {
        name: "minecraft:underwater_bonemeals",
        blocks: &[
            136, 763, 764, 765, 766, 767, 773, 774, 775, 776, 777, 783, 784, 785, 786, 787,
        ],
    },
    BlockTag {
        name: "minecraft:unstable_bottom_center",
        blocks: &[369, 628, 629, 630, 631, 632, 633, 634, 635, 636, 893, 894],
    },
    BlockTag {
        name: "minecraft:valid_spawn",
        blocks: &[8, 11],
    },
    BlockTag {
        name: "minecraft:vibration_resonators",
        blocks: &[978],
    },
    BlockTag {
        name: "minecraft:wall_corals",
        blocks: &[783, 784, 785, 786, 787],
    },
    BlockTag {
        name: "minecraft:wall_hanging_signs",
        blocks: &[246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257],
    },
    BlockTag {
        name: "minecraft:wall_post_override",
        blocks: &[
            194, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 224, 225, 226, 227, 228, 229,
            230, 231, 232, 233, 259, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 273, 280,
            290, 292, 402, 471, 472, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574,
            575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
            592, 593, 594, 887, 888, 901, 902, 903, 904, 938,
        ],
    },
    BlockTag {
        name: "minecraft:wall_signs",
        blocks: &[224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 903, 904],
    },
    BlockTag {
        name: "minecraft:walls",
        blocks: &[
            379, 409, 410, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 926,
            934, 940, 987, 991, 996, 1002, 1006, 1010, 1015, 1019, 1023, 1155, 1159, 1163, 1167,
        ],
    },
    BlockTag {
        name: "minecraft:warped_stems",
        blocks: &[862, 863, 864, 865],
    },
    BlockTag {
        name: "minecraft:wart_blocks",
        blocks: &[672, 868],
    },
    BlockTag {
        name: "minecraft:wither_immune",
        blocks: &[
            34, 156, 391, 392, 407, 524, 525, 667, 668, 669, 905, 906, 907, 908, 1182,
        ],
    },
    BlockTag {
        name: "minecraft:wither_immune_to",
        blocks: &[170],
    },
    BlockTag {
        name: "minecraft:wither_skeleton_immune_to",
        blocks: &[170],
    },
    BlockTag {
        name: "minecraft:wither_summon_base_blocks",
        blocks: &[286, 287],
    },
    BlockTag {
        name: "minecraft:wolves_spawnable_on",
        blocks: &[8, 10, 11, 276, 278],
    },
    BlockTag {
        name: "minecraft:wooden_buttons",
        blocks: &[443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 897, 898],
    },
    BlockTag {
        name: "minecraft:wooden_doors",
        blocks: &[220, 646, 647, 648, 649, 650, 651, 652, 653, 654, 899, 900],
    },
    BlockTag {
        name: "minecraft:wooden_fences",
        blocks: &[284, 637, 638, 639, 640, 641, 642, 643, 644, 645, 889, 890],
    },
    BlockTag {
        name: "minecraft:wooden_pressure_plates",
        blocks: &[261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 887, 888],
    },
    BlockTag {
        name: "minecraft:wooden_shelves",
        blocks: &[180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191],
    },
    BlockTag {
        name: "minecraft:wooden_slabs",
        blocks: &[599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 885, 886],
    },
    BlockTag {
        name: "minecraft:wooden_stairs",
        blocks: &[200, 404, 405, 406, 516, 517, 518, 519, 520, 521, 895, 896],
    },
    BlockTag {
        name: "minecraft:wooden_trapdoors",
        blocks: &[316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 891, 892],
    },
    BlockTag {
        name: "minecraft:wool",
        blocks: &[
            140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        ],
    },
    BlockTag {
        name: "minecraft:wool_carpets",
        blocks: &[
            538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553,
        ],
    },
];
